// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxvdsyjkhjmdiascvqme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4dmRzeWpraGptZGlhc2N2cW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzI0MzgsImV4cCI6MjA3MDA0ODQzOH0.lkY9uTof8hkmRJBzybCas4S9XIKDplsN3Qb-2dWg7uU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});